spring.application.name=branch

spring.cloud.consul.enabled=false

# Configuración de PostgreSQL (ajusta host, puerto, nombre de BD, usuario y contraseña según tu entorno)
spring.datasource.url=jdbc:postgresql://localhost:5432/branch_db
spring.datasource.username=postgres
spring.datasource.password=123

# Hibernate: creación/actualización automática de las tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto en el que se ejecuta el servicio
server.port=8080

# Configuración de Consul (opcional)
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=${spring.application.name}

# Swagger/OpenAPI: La UI estará disponible en /swagger-ui/index.html
